### ISSUE TITLE
Build fails on Solaris

### ISSUE THREAD

**Issue by yvoinov** [skeeto/endlessh#14]
```# make
cc -ggdb3 -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Os -o endlessh endlessh.c 
cc: Warning: Option -db3 passed to ld, if ld is invoked, ignored otherwise
cc: Warning: Option -Os passed to ld, if ld is invoked, ignored otherwise
"/usr/include/sys/feature_tests.h", line 337: #error: "Compiler or options invalid for pre-UNIX 03 X/Open applications  and pre-2001 POSIX applications"
cc: acomp failed for endlessh.c
make: *** [Makefile:8: endlessh] Error 2

cc on Solaris is Oracle Developer Studio.

When change to gcc, got different errors:

# make
gcc -ggdb3 -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Os -o endlessh endlessh.c 
In file included from /usr/include/time.h:18:0,
                 from endlessh.c:20:
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.5.0/include-fixed/sys/feature_tests.h:346:2: error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications       and pre-2001 POSIX applications"
 #error "Compiler or options invalid for pre-UNIX 03 X/Open applications \
  ^
In file included from /usr/include/sys/vnode.h:44:0,
                 from /usr/include/sys/stream.h:21,
                 from /usr/include/netinet/in.h:65,
                 from /usr/include/sys/socket.h:44,
                 from endlessh.c:32:
/usr/include/sys/resource.h:146:17: error: field 'ru_utime' has incomplete type
  struct timeval ru_utime; /* user time used */
                 ^
/usr/include/sys/resource.h:147:17: error: field 'ru_stime' has incomplete type
  struct timeval ru_stime; /* system time used */
                 ^
endlessh.c:152:8: error: redefinition of 'struct queue'
 struct queue {
        ^
In file included from /usr/include/netinet/in.h:65:0,
                 from /usr/include/sys/socket.h:44,
                 from endlessh.c:32:
/usr/include/sys/stream.h:66:16: note: originally defined here
 typedef struct queue {
                ^
endlessh.c: In function 'config_load':
endlessh.c:419:16: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
         while (getline(&line, &len, f) != -1) {
                ^
endlessh.c: In function 'main':
endlessh.c:566:22: warning: implicit declaration of function 'getopt' [-Wimplicit-function-declaration]
     while ((option = getopt(argc, argv, "d:f:hl:m:p:vV")) != -1) {
                      ^
endlessh.c:569:43: error: 'optarg' undeclared (first use in this function)
                 config_set_delay(&config, optarg, 1);
                                           ^
endlessh.c:569:43: note: each undeclared identifier is reported only once for each function it appears in
endlessh.c:602:14: error: 'optind' undeclared (first use in this function)
     if (argv[optind]) {
              ^
make: *** [Makefile:8: endlessh] Error 1

**Comment by yvoinov** [comment]
Well, when I add -D_XPG6, error gone, but still has timeval issue:

**Comment by skeeto** [comment]
I don't have access to a Solaris system, but on illumos-based systems 
I can successfully build like so:

make CFLAGS='-Os -D__EXTENSIONS__=1' LDLIBS='-lsocket -lnsl'

The __EXTENSIONS__ definition is to get a prototype for getline(3). 
There's a conformance bug in illumos (and perhaps Solaris): getline(3) 
should be declared when _POSIX_C_SOURCE >= 200809L, but illumos treats 
it as if it were still a non-standard extension. They also don't 
document this fact.

The error you're seeing is different, though. I guess Solaris doesn't 
like the C compiler running in C99 mode while asking for POSIX.1-2008? 
Unfortunately this sort of thing is typical Solaris nonsense, and I've 
never been able to figure out how to resolve these things. Fortunately 
illumos (and family) has shed a lot of it. Maybe try -std=c11 instead?

The first warning is just that Solaris doesn't know about -ggdb3, which 
is fine. You don't need that option. The second is strange. Is it not 
seeing -Os as an optimization flag?

**Comment by yvoinov** [comment]
Oh, yeah. Thanks for remember me EXTENSIONS. ;) Forgot about it.

Now, any progress:

cc  -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -D_XPG6 -D__EXTENSIONS__=1 -o endlessh endlessh.c 
"endlessh.c", line 152: (struct) tag redeclared: queue
"endlessh.c", line 419: warning: implicit function declaration: getline
cc: acomp failed for endlessh.c
make: *** [Makefile:8: endlessh] Error 2

It seems queue is keyword.

Yes, -Os is only opt flag in gcc/clang. In Solaris cc opt prefixes is -xOn, and they has different. -xO4 will correct.

**Comment by yvoinov** [comment]
After some experimens and corrections with code (PR #17) working combinations found:

CC      = cc
CFLAGS  = -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -D_XPG6 -D__EXTENSIONS__=1
LDFLAGS =
LDLIBS  = -lsocket -lnsl -lrt

Just remains some warnings:

cc  -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -D_XPG6 -D__EXTENSIONS__=1 -o endlessh endlessh.c -lsocket -lnsl -lrt
"endlessh.c", line 420: warning: argument #1 is incompatible with prototype:
        prototype: restrict pointer to char : "/usr/include/iso/stdio_iso.h", line 220
        argument : pointer to pointer to char
"endlessh.c", line 420: warning: improper pointer/integer combination: arg #2
"endlessh.c", line 420: warning: improper pointer/integer combination: op "!="

seems require cast with Oracle Developer Studio (early it shown strict requirements to pointer types and casts). :) Will dig.

**Comment by yvoinov** [comment]
Warnings remains related fgets(), which is in stdio_iso.h as follows:

extern char	*fgets(char *_RESTRICT_KYWD, int, FILE *_RESTRICT_KYWD);

**Comment by yvoinov** [comment]
At least block

	#ifdef __sun__	
        while (fgets(&line, len, f) != -1) {
	#else

in PR#17 should be len as value, not as pointer. This reduces warnings to one:

cc  -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -D_XPG6 -D__EXTENSIONS__=1 -o endlessh endlessh.c -lsocket -lnsl -lrt
"endlessh.c", line 420: warning: argument #1 is incompatible with prototype:
        prototype: restrict pointer to char : "/usr/include/iso/stdio_iso.h", line 220
        argument : pointer to pointer to char
"endlessh.c", line 420: warning: improper pointer/integer combination: op "!="

:)

**Comment by yvoinov** [comment]
Fixed. PR #17

**Comment by skeeto** [comment]
I took a different approach with b1c1599d. No need to worry about 
__EXTENSIONS__ on the command line, it just sets it in the source. I 
also went with "fifo" instead of "v_queue". Lastly, note the special 
instructions in the README.

Let me know if there's anything I missed. I only tested on OpenIndiana 
and OmniOS, and neither of those use the Sun's cc. Thanks!

**Comment by yvoinov** [comment]
> 
> I took a different approach with [b1c1599](https://github.com/skeeto/endlessh/commit/b1c1599d32556171c6b28f772fa46285a62ca6aa). No need to worry about __EXTENSIONS__ on the command line, it just sets it in the source. I also went with "fifo" instead of "v_queue". Lastly, note the special instructions in the README. Let me know if there's anything I missed. I only tested on OpenIndiana and OmniOS, and neither of those use the Sun's cc. Thanks!

Yes, this will much better. Will test again updated. Thank you!

**Comment by skeeto** [comment]
What version of Solaris are you running? It must be pretty old if it 
doesn't have getline(3) even through __EXTENSIONS__.

I simplified a bunch of things in 9f4bdc1, retreated to POSIX.1-2001, 
and now I believe Solaris no longer requires special treatment except 
for passing those extra libraries to the linker.

**Comment by yvoinov** [comment]
SunOS khorne 5.10 Generic_150401-64
Release 1/13, latest patch.

Will check https://github.com/skeeto/endlessh/commit/9f4bdc123dc4f111baa537cd5312736c2206b2f7

**Comment by yvoinov** [comment]
Note: -D__EXTENSIONS__=1 still requires, without get build error:

cc  -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -o endlessh endlessh.c -lsocket -lnsl -lrt
"endlessh.c", line 70: undefined symbol: INET6_ADDRSTRLEN
"endlessh.c", line 70: can not declare variably modified type at file scope
"endlessh.c", line 460: undefined symbol: in6addr_any
cc: acomp failed for endlessh.c
make: *** [Makefile:10: endlessh] Error 2

Successfully built new code with CFLAGS  = -std=c99 -Wall -Wextra -Wno-missing-field-initializers -xO4 -D__EXTENSIONS__=1 and LDLIBS  = -lsocket -lnsl -lrt

**Comment by skeeto** [comment]
Ah, so you're essentially running an operating system from 2005! That 
explains why you're completely missing some things. What happens if you 
change the feature test macro on the first line to:

#define _XOPEN_SOURCE 600

Some research suggests this is required to get IPv6 definitions, and 
that _POSIX_C_SOURCE 200112L isn't quite enough.

**Comment by yvoinov** [comment]
> 
> Ah, so you're essentially running an operating system from 2005! That explains why you're completely missing some things. What happens if you change the feature test macro on the first line to: #define _XOPEN_SOURCE 600 Some research suggests this is required to get IPv6 definitions, and that _POSIX_C_SOURCE 200112L isn't quite enough.

Generally speaking, from 2013 :) 1/13 is latest point release and it's updated up to 2019 patch level. Imagine, it's still supported :)

NB: IPv6 supported by Sol 10, ever from release 5/05 :)

With macro #define _XOPEN_SOURCE 600 is same like previous (all ok), if -D__EXTENSIONS__=1 specified.
