### ISSUE TITLE
Build failure on BSD

### ISSUE THREAD

**Issue by pacocc** [skeeto/endlessh#2]
endlessh> make

cc -ggdb3 -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Os -o endlessh endlessh.c 
endlessh.c:705:55: error: use of undeclared identifier 'MSG_DONTWAIT'
                    ssize_t out = send(fd, line, len, MSG_DONTWAIT);
                                                      ^
1 error generated.
*** Error code 1

Stop.

**Comment by skeeto** [comment]
So MSG_DONTWAIT is a non-standard, though very widely supported send(2) 
flag. FreeBSD _does_ support it, but unfortunately it hides the flag 
definition when _POSIX_C_SOURCE is defined. While this is generally the 
technically correct thing to do — hide non-standard features when a 
specific standard is requested — this choice makes the flag essentially 
impossible to use correctly: send(2) itself shouldn't be visible without 
the proper _POSIX_C_SOURCE definition either. It also doesn't help that 
FreeBSD is the only platform with this particular behavior. None of the 
other platforms I've tested on hides this flag (though OpenSolaris-based 
systems don't seem to support it at all?).

Anyway, the simplest thing to do is just remove the first line of the 
file that defines _POSIX_C_SOURCE, and it will build just fine. FreeBSD 
(nor the other BSDs) has never been precise about feature test macros 
anyway.

The _think_ actual correct, portable thing to do is to put the socket 
non-blocking mode using fcntl(2). MSG_DONTWAIT is just a convenience for 
making the socket non-blocking for that send(2).

**Comment by felix021** [comment]
a funny project~ since it's not a CPU intensive task, python or go may be a better choice, more portable with a smaller code base.
