### ISSUE TITLE
inaccurate time in log message

### ISSUE THREAD

**Issue by Smattr** [skeeto/endlessh#26]
Line 150-154 has the following:

```c
    logmsg(LOG_INFO, "TOTALS connects=%lld seconds=%lld.%lld bytes=%lld",
           statistics.connects,
           milliseconds / 1000,
           milliseconds % 1000,
           statistics.bytes_sent);
```

I think the format code for the milliseconds remainder should be `%03lld` like line 135, right? Otherwise, e.g. 1005 milliseconds, will be printed as "seconds=1.5".

Nice project by the way! Very creative idea :)

**Comment by skeeto** [comment]
You're right, thanks! Fixed in 370cb5b.
