### ISSUE TITLE
Error in manpage?

### ISSUE THREAD

**Issue by nbraud** [skeeto/endlessh#35]
Lintian (the Debian package linter) [reports] a syntax issue in the manpage, but I'm incapable of narrowing it down to a specific issue (it's 2.30am here, I'm not dealing with troff...)

[reports]: https://ftp-master.debian.org/new/endlessh_1.0-1.html#binary-endlessh-lintian-wrap

**Comment by skeeto** [comment]
I'm on Debian and I installed Lintian for this, but I couldn't figure 
out how to run it on the man page specifically. Fortunately groff was 
already complaining about the same thing, so I just used it to key in on 
the issue. I believe it's fixed now.

**Comment by nbraud** [comment]
@skeeto I can confirm the linked commit fixed the Lintian warning.  Thanks a lot for the fix  :)

(I don't think you can run Lintian on anything else than a Debian package (source or binary), but it probably relies on groff for linting manpages (though I don't feel like checking the source).)
