### ISSUE TITLE
endlessh wont start

### ISSUE THREAD

**Issue by ScHaTTeNLiLiE** [skeeto/endlessh#47]
```
-- The start-up result is done.
Okt 24 12:38:29 monsterchen systemd[1]: Reloading.
Okt 24 12:41:00 monsterchen systemd[1]: Reloading.
Okt 24 12:41:07 monsterchen systemd[1]: Started Endlessh SSH Tarpit.
-- Subject: Unit endlessh.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit endlessh.service has finished starting up.
--
-- The start-up result is done.
Okt 24 12:41:07 monsterchen endlessh[1570]: 2020-10-24T10:41:07.138Z Port 22
Okt 24 12:41:07 monsterchen endlessh[1570]: 2020-10-24T10:41:07.138Z Delay 10000
Okt 24 12:41:07 monsterchen endlessh[1570]: 2020-10-24T10:41:07.138Z MaxLineLength 32
Okt 24 12:41:07 monsterchen endlessh[1570]: 2020-10-24T10:41:07.138Z MaxClients 4096
Okt 24 12:41:07 monsterchen endlessh[1570]: 2020-10-24T10:41:07.138Z BindFamily IPv4 Mapped IPv6
Okt 24 12:41:07 monsterchen endlessh[1570]: endlessh: fatal: Permission denied
Okt 24 12:41:07 monsterchen systemd[1]: endlessh.service: Main process exited, code=exited, status=1/FAILURE
Okt 24 12:41:07 monsterchen systemd[1]: endlessh.service: Failed with result 'exit-code'.
```
[root@monsterchen ~]# sestatus
SELinux status:                 disabled

**Comment by ROT-userhandle** [comment]
Maybe I need to build this again?

sudo systemctl status endlessh
● endlessh.service - Endlessh SSH Tarpit
     Loaded: loaded (/etc/systemd/system/endlessh.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-10-24 20:59:11 UTC; 7s ago
       Docs: man:endlessh(1)
    Process: 7915 ExecStart=/usr/local/bin/endlessh (code=exited, status=1/FAILURE)
   Main PID: 7915 (code=exited, status=1/FAILURE)




**journalct -xe returns the following:** 
endlessh.service: Start request repeated too quickly.
Oct 24 21:02:14 username systemd[1]: endlessh.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit endlessh.service has entered the 'failed' state with result 'exit-code'.
Oct 24 21:02:14 username systemd[1]: Failed to start Endlessh SSH Tarpit.
-- Subject: A start job for unit endlessh.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit endlessh.service has finished with a failure.
--
-- The job identifier is 4878 and the job result is failed.


Just thought I'd ask. Either way, I'm happy to test this further. Will come back later with fresh eyes.
