### ISSUE TITLE
Systemd won't start

### ISSUE THREAD

**Issue by nunocruz** [skeeto/endlessh#50]
I am trying to get this to run in a raspbian system. If I start the application on it's own it works fine, but by trying to make it run throught systemctl I get this:

`ExecStart=/usr/local/bin/endlessh (code=exited, status=226/NAMESPACE)`

I followed the endlessh.service instructions to run it in a port under 1028, which initially I failed to follow, but I still get the same result.

**Comment by hamburghammer** [comment]
Do you get some more information about the service error messages?
What are the last entries running `journalctl -u endlessh.service`?
If you run it with a port > 1028 do you still have this problem?

**Comment by nunocruz** [comment]
> What are the last entries running journalctl -u endlessh.service?
```
Nov 04 12:52:49 raspberrypi systemd[1]: Started Endlessh SSH Tarpit.
Nov 04 12:52:49 raspberrypi systemd[1]: endlessh.service: Main process exited, code=exited, status=226/NAMESPACE
Nov 04 12:52:49 raspberrypi systemd[1]: endlessh.service: Unit entered failed state.
Nov 04 12:52:49 raspberrypi systemd[1]: endlessh.service: Failed with result 'exit-code'.
Nov 04 12:53:09 raspberrypi systemd[1]: Stopped Endlessh SSH Tarpit.
Nov 04 13:00:38 raspberrypi systemd[1]: [/etc/systemd/system/endlessh.service:36] Unknown lvalue 'ConfigurationDirectory' in section 'Service'
```

I did encounter the same problem when trying to run on ports > 1028

**Comment by nunocruz** [comment]
It seems it was the version of the OS which was outdated. After updating the the lastest raspberry pi image, this issue is gone.
