### ISSUE TITLE
[announcement] Multi-arch docker image by linuxserver.io released

### ISSUE THREAD

**Issue by aptalca** [skeeto/endlessh#65]
Hey guys, not a bug but an announcement really.

We, [LinuxServer.io](https://linuxserver.io), just released a multi-arch docker image (x86_64, arm32v7 and arm64v8) for Endlessh, pushed to Docker Hub, GHCR and Gitlab.

The readme is here: https://github.com/linuxserver/docker-endlessh

In a nutshell, you can run it as a stateless container, configured via env vars, logging to container log. You can also have it log to file if you want to pair it with fail2ban (not included).

The endlessh process runs as an unprivileged user inside the container and it listens on port 2222, but you can map that to any port on the host (including 22). The image gets weekly OS package updates, and will automatically build and push any commits to the master repo here.

Enjoy!

PS. Thanks @skeeto for the code. We included the donation link for https://secure.givewell.org/ in the container log and in the Github sponsors button based on your blog entry about it. We hope that's OK.

**Comment by skeeto** [comment]
> We hope that's OK.

Yup, that's a great idea! Thanks!
