### ISSUE TITLE
TCP v4 is not default

### ISSUE THREAD

**Issue by mrx23dot** [skeeto/endlessh#79]
During install all I configured is :
```
  sudo nano /etc/endlessh/config
    Port 6000
```0

then it only listens on tcp6:

```
 sudo netstat -ntulp | grep end
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::60000                :::*                    LISTEN      355519/endlessh
```

How can I also enable tcp4 too? 
And why isn't default?

**Comment by 0xphk** [comment]
You can configure the bindfamily in the config file ```/etc/endlessh/config``` as clearly stated in the README.md
```
# Set the family of the listening socket
#   0 = Use IPv4 Mapped IPv6 (Both v4 and v6, default)
#   4 = Use IPv4 only
#   6 = Use IPv6 only
BindFamily 4
```

**Comment by mrx23dot** [comment]
Works okay, thanks.
Not sure about the default mixed value, I have only had problems with ipv6 in home network.
